env:
  global:
    - secure: "DOJzjXBuRa9XJe+ByOgzD0qW9U4FFdif5vUzuQIz0FXQIJW9ghYUY5Pt4DCPDMuYQ/GHB4dN6jnA8SQz6Rthsd8p+qwHp7U6yWYTNIhbaL5zsE8BICWmrclROv6/9+2KLe70/a+94xOyVjI7x1rHsAkOuWDb8839OfAmRkJpZ8C1WZ5lRtUDNJ77U9SuxragCG3pZJymHsZbsVV1rU1FgdmNm8fzyp2dHI5DmEYfHXNo5SUMPKvfVj59iYaS8j8yIL7HltUB8bKbGufUdLVsznzS0GIJCdgI87E2XivM1aT3RGRrOO/eLLul3h3L2+M0rrM842oUSE3U4Byw8jW+BaF6D0Dkw4Appvh15X1gBc/l9TMF8SARUOMUWxgLkbeOwR5h1mO9N9r5dvelbYiGZ8VnWLgkTfa1XJhkjShXUtKx20lci0Hp6rIKb7mWgp8be/TVxzWqThWlACLkxhv5pu53k9oUYyZied0W4bjqYeIviVMcLzkzle1OlChy0IXF4EfzZtZ3P+ec/WhSNgEo7Z5n4UwrTF3bOOknh2RB09hynFWaQbJU/9lf6PcUyRf6EDxhJ61XRPCWdAPAhVBlu29DgpjuaHX6OUiHRsk3HzdEETP0ooNxJVEfiKRE/QDB3GmDq5sgyYB/OEhCFdyJ+owWynaVv10uAMYF/IJH8aQ=" # DOCKER_EMAIL
    - secure: "OFaVc4wPj2/3K02XN1rxXokq743Jem517YVUKoJj26PAMcd1Edxf8WNsVonpl7/r0KtnSJdxoRZY5vGSbVXBHtFdxkbKAZ6NE6+n2rTwgokt4BP0njC7LN8OJ7QDsfMHlTYpIGVz9qWmoBpJ9kQ6EJ54InOZXru7XlCaPsQZZpgIMVttkkSN/R2vOfrCPl9HmCJF/fAO/2ufPvuioP6o1ZgkTcDSJGSukKzPhAXfuFnkMz9qWliGncnXLfmuGswAICwXbjtEIopJjjsoIjIP0R8QCvrabIYMsNY3COIqqzhGNhcJnEAT/W0Ae323xmRbrYUa+fKb2g/oykmKZlqsFNFydM2BYVo1jupC1UzBXZSTMW4BMj6OmZ9jcT0/oqQAcfwIMWQLWET4fzEWa68te/+ewfq2gG5EgpCgrFXLz6gmcSAnc3+VnUG9+qVf7AHAkqRTfo6mE8pDK0MeZ/xiyTOFnhbDk1KqculroIxCGJWH6T5vJYtHgaxhjRclB+yjkxAg0sH8mtMrgVv2vjVS3z3YcrgWwy9CKFi0GKQthImMytjjn3Zdrxnm/co2JPNjspiS+oiyVegnBWSj53wL+oxep4rW456UCflYwmJWmkyE5a5/NCwyhEZ6xCYy2Nl1vCj4EKLwZbANEQx+lxEUJEepOKynrw7QsKeNKRw+uFQ=" # DOCKER_USER
    - secure: "lS8cCU1xORTTGd9+Tn1L6gB97FdPAZ5vqXNKm59TM+qsdQPqLtvVZINkmTz+opmm518+M7r7e0YNVM0+y+N6up5uDJTavQ+X9oUAE4laRMxn/MJdX4wVYRvsz2iMqXyPwdANmRqUfjoG5cjXOkBpEV18+4UpIKi/Xkqys6/bYev6TDWQaLpflxSy0Fi5GLQrpizQuDf8bHlZJOq8Tos3+VpUI2mXW/bFFbxsbPGEkDIsQRtyVWeGPHlM+1/lhnkdah+6sEC3llDYOXV17sBlG833YtCD5DrDaA/uUVpzZyASKERs2137sq62Al+9C03r+sZZFWXms/KvJhi5A9UBrGfeDTMw0bHuF9aeJo0wXP6I3lYLcWhXWCxX6MVCEtTKRtowLe1+U3s+gkkYIoBkn41WBN3+nvPvTHiU9AVefkd3vRnCxdV399a1MC61FAnz/O1YhSfUZtwB52g+l/ZMCnpVVfSy5usAz4PPjVAlkwzpcR+qK5x7UcrpYmYBESjJ7+cPfvixIHttspsQjf5qkcADwP8krKm1sFAQWM+sUd88z17fyoU3FhrTU+FFLVywboB22Z+s7X0Q4wM8pdVuc8LmJ7QhVcfeEPrJj8DPvnpmNyF/boiKeE8dVRhQlXKoQNELodiBNfEqa5EraCmDIdtUsv8fZnEgkkF/o3P9ATM=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}

sudo: required

language: node_js

node_js:
  - "node"

script: "sudo $(which npm) test"

services:
  - docker

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=brunopadz/nightwatch-dockder
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
